# Generated by Django 2.0.4 on 2018-05-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180425_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='post',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
